# Generated by Django 5.0.1 on 2024-08-08 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction_type', '0002_transactiontable'),
    ]

    operations = [
        migrations.CreateModel(
            name='WalletTable',
            fields=[
                ('wallet_id', models.CharField(blank=True, editable=False, max_length=100, primary_key=True, serialize=False, unique=True)),
                ('mobile_number', models.CharField(max_length=15, unique=True)),
            ],
            options={
                'db_table': 'wallet_table',
            },
        ),
    ]
