# Generated by Django 5.0.1 on 2024-08-09 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction_type', '0003_wallettable'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactiontable',
            name='related_wallet',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='wallettable',
            name='balance',
            field=models.DecimalField(decimal_places=8, default=0.0, max_digits=18),
        ),
    ]
