# Generated by Django 5.0.1 on 2024-08-09 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transaction_type', '0004_transactiontable_related_wallet_wallettable_balance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transactiontable',
            name='related_wallet',
        ),
        migrations.RemoveField(
            model_name='wallettable',
            name='balance',
        ),
    ]
