# Generated by Django 5.0.1 on 2024-08-09 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction_type', '0005_remove_transactiontable_related_wallet_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wallet_id', models.CharField(max_length=100, unique=True)),
                ('mobile_number', models.CharField(max_length=15)),
                ('fiat_address', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'db_table': 'address',
            },
        ),
    ]
