# Generated by Django 5.0.1 on 2024-08-09 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction_type', '0006_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddressBasedTransaction',
            fields=[
                ('transaction_id', models.CharField(blank=True, editable=False, max_length=100, primary_key=True, serialize=False, unique=True)),
                ('transaction_type', models.CharField(max_length=50)),
                ('transaction_amount', models.DecimalField(decimal_places=8, max_digits=18)),
                ('transaction_currency', models.CharField(max_length=10)),
                ('transaction_timestamp', models.DateTimeField(auto_now_add=True)),
                ('transaction_status', models.CharField(max_length=50)),
                ('transaction_hash', models.CharField(blank=True, editable=False, max_length=255, unique=True)),
                ('transaction_fee', models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True)),
                ('person_phone_number', models.CharField(max_length=15)),
                ('fiat_address', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'db_table': 'address_based_transaction',
            },
        ),
    ]
