# Generated by Django 5.0.1 on 2024-08-09 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction_type', '0007_addressbasedtransaction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addressbasedtransaction',
            name='person_phone_number',
        ),
        migrations.RemoveField(
            model_name='addressbasedtransaction',
            name='transaction_fee',
        ),
        migrations.AlterField(
            model_name='addressbasedtransaction',
            name='fiat_address',
            field=models.CharField(max_length=255),
        ),
    ]
