# Generated by Django 5.0.1 on 2024-08-16 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction_type', '0010_alter_user_name_alter_user_qr_code'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Address',
        ),
        migrations.DeleteModel(
            name='AddressBasedTransaction',
        ),
        migrations.DeleteModel(
            name='WalletTable',
        ),
        migrations.RemoveField(
            model_name='transactiontable',
            name='person_phone_number',
        ),
        migrations.AddField(
            model_name='transactiontable',
            name='fiat_address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='transactiontable',
            name='sender_mobile_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='transactiontable',
            name='transaction_description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='transactiontable',
            name='user_phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='transactiontable',
            name='wallet_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='transactiontable',
            name='transaction_amount',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='transactiontable',
            name='transaction_currency',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='transactiontable',
            name='transaction_status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='transactiontable',
            name='transaction_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
