# Generated by Django 5.0.7 on 2024-09-04 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TransactionTable',
            fields=[
                ('transaction_id', models.CharField(blank=True, editable=False, max_length=100, primary_key=True, serialize=False, unique=True)),
                ('transaction_type', models.CharField(blank=True, max_length=50, null=True)),
                ('transaction_amount', models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True)),
                ('transaction_currency', models.CharField(blank=True, max_length=10, null=True)),
                ('transaction_timestamp', models.DateTimeField(auto_now_add=True)),
                ('transaction_status', models.CharField(blank=True, max_length=50, null=True)),
                ('transaction_hash', models.CharField(max_length=255, unique=True)),
                ('transaction_fee', models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True)),
                ('user_phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('wallet_id', models.CharField(blank=True, max_length=100, null=True)),
                ('sender_mobile_number', models.CharField(blank=True, max_length=15, null=True)),
                ('fiat_address', models.CharField(blank=True, max_length=255, null=True)),
                ('transaction_method', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'transaction_table',
            },
        ),
        # migrations.CreateModel(
        #     name='User',
        #     fields=[
        #         ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        #         ('name', models.CharField(max_length=100)),
        #         ('mobile_number', models.CharField(max_length=15)),
        #         ('qr_code', models.TextField(blank=True, null=True)),
        #     ],
        #     options={
        #         'db_table': 'registration',
        #     },
        # ),
    ]
