# Generated by Django 5.0.7 on 2024-08-27 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactiontype', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transactiontable',
            old_name='transaction_description',
            new_name='transaction_method',
        ),
    ]
