# Generated by Django 5.0.1 on 2024-10-30 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactiontype', '0002_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Project',
        ),
    ]
